AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zaufakturybe

  SAM Template for zaufakturybe

Parameters:
  TableContactsName:
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: Required. Can be characters and underscore only. No numbers
      or special characters allowed.
    Default: TableContacts
    Description: (Required) The name of the new DynamoDB to store connection identifiers
      for each connected clients. Minimum 3 characters
    MaxLength: 50
    MinLength: 3
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  TableContacts:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "contactId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "contactId"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: 
        Ref: TableContactsName
  AgendaListContactsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: account/
      Handler: agenda.list_contacts
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /account/agenda/listcontacts
            Method: get
      Policies:
      - DynamoDBCrudPolicy:
          TableName: 
            Ref: TableContactsName
  AgendaSaveContactFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: account/
      Handler: agenda.save_contact
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /account/agenda/savecontact
            Method: post
      Policies:
      - DynamoDBCrudPolicy:
          TableName: 
            Ref: TableContactsName
  AgendaDeleteContactFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: account/
      Handler: agenda.delete_contacts
      Runtime: python3.7
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /account/agenda/deletecontact
            Method: delete
      Policies:
      - DynamoDBCrudPolicy:
          TableName: 
            Ref: TableContactsName


Outputs:
  AgendaApi:
    Description: "API Gateway endpoint URL for listing contacts"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/account/agenda/listcontacts"
  AgendaFunction:
    Description: "Agenda List Contacts ARN"
    Value: !GetAtt AgendaListContactsFunction.Arn
  AgendaFunctionIamRole:
    Description: "Implicit IAM Role created for Agenda List Contacts function"
    Value: !GetAtt AgendaListContactsFunctionRole.Arn
